datacube_alchemist/cli.py
=> add rudimentary timer

datacube_alchemist/__init__.py, datacube_alchemist/_dask.py, datacube_alchemist/cli.py, datacube_alchemist/upload.py, datacube_alchemist/worker.py, examples/DEAfrica_wofs_c2_no_dsm.yaml, setup.py
This PR does two things. (:sadface:)
1. Allow customising the resampling method used for writing overviews.
2. Use setuptools_scm to provide better version numbers.
=> Customise resampling method of overviews

Dockerfile, datacube_alchemist/cli.py, datacube_alchemist/worker.py, requirements.txt, tests/test_datacube_alchemist.py
Having the uuid deterministic.
For sentinel data writing the output to a uuid directory.
=> Deterministic UUIDs

.github/workflows/datacube-alchemist.yml, setup.py
Switch to the cached build action
=> Add cached build and tag pushing

.github/workflows/datacube-alchemist.yml, Dockerfile, Makefile
Fix issue where `datacube-alchemist` command wasn't being found
=> Fix prod docker image

Makefile, datacube_alchemist/cli.py, docker-compose.yml, examples/fc_config_sentinel2b_test.yaml
=> Include a docker compose dev environment

datacube_alchemist/cli.py, datacube_alchemist/worker.py
* This is a failed attempt at using STAC for the content of pushed messages
* It doesn't work because EO Datasets uses a DatasetDoc and not a Dataset to store information about a dataset. This is not helpful
=> Update message content

.pre-commit-config.yaml, datacube_alchemist/_dask.py, datacube_alchemist/_utils.py, datacube_alchemist/cli.py, datacube_alchemist/settings.py, datacube_alchemist/worker.py, examples/c3_config_fc.yaml, requirements.txt, setup.py
- Delete messages from queue when processed
- Don't `len()` a generator
- Some formatting, with updated `pre-commit` config
- Cleaner requirements
What are you running to test within docker? There's a LOT in the Makefile...
=> A few fixes

Dockerfile, datacube_alchemist/worker.py
=> Deployment fixes

Makefile, datacube_alchemist/_utils.py, datacube_alchemist/cli.py, datacube_alchemist/settings.py, datacube_alchemist/worker.py, examples/c3_config_fc.yaml, examples/c3_config_wo.yaml
1. Use EODatasets to write the singleband thumbnail
2. Set the flag to copy valid_data extents over instead of calculating them
=> Implement eodatasets changes

datacube_alchemist/_utils.py, datacube_alchemist/cli.py, datacube_alchemist/worker.py
=> Fixes and sns

datacube_alchemist/cli.py
- Actually implement the queue to queue thing
=> Implement the queue redrive function properly

Dockerfile, datacube_alchemist/_utils.py, datacube_alchemist/cli.py, datacube_alchemist/worker.py, requirements.txt, setup.py
- big fix is STAC links
- smaller is loads of other bits
=> Little fixes

datacube_alchemist/_utils.py, examples/c3_config_wo.yaml
- fix wofs config
- fix S3 URI for STAC
=> Fix S3 URI wrangling

datacube_alchemist/worker.py
- 1.7 seconds for 300 messages rather than 11 seconds
- Also provides feedback as it goes using `sys.stdout.write(f"\rAdded {count} messages...")`, which I think is an ok approach
=> Do bulk message posting

datacube_alchemist/_utils.py, datacube_alchemist/worker.py
Pretty simple change. Basically don't copy the GSD from the input data.
=> Get the GSD from output resolution

examples/c3_config_wo.yaml
Simple, default nodata to black
=> Make the nodata black

datacube_alchemist/_utils.py, datacube_alchemist/cli.py, datacube_alchemist/worker.py
* Include log level in log messages so we can filter easier
* Make a helper function to help us
=> Set up logging so that it includes the level

datacube_alchemist/_utils.py, datacube_alchemist/cli.py, datacube_alchemist/worker.py, docker-compose.yml
Mixing up a few things in here:
- Do logging better, following datacube-explorer's lead
- Use a better postgres image and not postgis
=> Make logging do it a better way again

.github/workflows/test.yml, Makefile, datacube_alchemist/cli.py, setup.py, tests/integration_tests.sh
=> Fixing the Integration Tests (wip)

datacube_alchemist/worker.py
Because it has 'error' in it and pollutes my …search for real errors
=> Don't log the S3 command 

Makefile
Just cleaning up the Makefile for manual testing.
=> Add real example datasets

datacube_alchemist/worker.py
Fail fast on archived datasets
=> Add a check for the dataset being archived

Makefile, datacube_alchemist/cli.py, datacube_alchemist/worker.py
This will run a custom SQL query to search for parent datasets that don't have child datasets. The SQL is simple. The finding of the child product ID is ... not!
Do you have any suggestions, @jeremyh or @omad to prevent the crazy workaround I have currently?
(I can share code with that section in how it's done later too... I think you'll see what I mean, though)
=> Add fill missing command and example

.github/workflows/push.yml, .github/workflows/test.yml, setup.py
=> Update to 0.17 eodatasets, which includes better COGging

datacube_alchemist/settings.py, datacube_alchemist/worker.py, examples/c3_config_fc.yaml, examples/c3_config_wo.yaml, tests/test_datacube_alchemist.py
* Use the datacube util to configure AWS
* Use less Dask chunks in example configs (need to fix in dev and prod configs)
=> Change GDAL and DASK configuration to make less requests

datacube_alchemist/settings.py, datacube_alchemist/worker.py, tests/c3_config_wo_noresampling.yaml, tests/c3_config_wo_resampling.yaml, tests/conftest.py, tests/test_datacube_alchemist.py
This PR adds an optional `resampling` argument to the Alchemist config.
=> Added resampling argument

datacube_alchemist/cli.py, datacube_alchemist/worker.py
* Adds a dryrun argument to the `add-to-queue` function
* Simplifies the `redrive-to-queue` so that you don't need to provide a destination queue
=> Add a simplified redrive-to-queue process and dryrun capabilities

setup.py
=> Update eodatasets3 to fix Sentinel 2 clobbering

Makefile, datacube_alchemist/_utils.py, datacube_alchemist/settings.py, datacube_alchemist/transforms.py, examples/c3_config_dnbr.yaml, examples/c3_config_dnbr_3band.yaml, examples/c3_config_fc.yaml, examples/c3_config_wo.yaml, requirements.txt
Implements 3-band burnscar process (dNBR, BSI and NDVI).
=> Dnbr sentinel 2 nrt

Makefile, datacube_alchemist/worker.py, examples/c3_config_fc.yaml, examples/wofs_ls.alchemist.yaml, requirements.txt, setup.py
* Fix a small bug when there's no properties passed in
* Add examples to the Makefile
* Add sample config for DE Africa.
=> Working test config for DE Africa WOfS

datacube_alchemist/_utils.py, datacube_alchemist/worker.py
Fixes two issues as per the title.
=> Fix S3 writing to root folder and SNS without maturity field

datacube_alchemist/cli.py, setup.py, tests/test_datacube_alchemist.py
* Love `moto`, thanks @whatnick!
=> Add test for empty queue

examples/wofs_ls.alchemist.yaml, requirements.txt
Issue is described over here: https://github.com/GeoscienceAustralia/wofs/issues/41
=> Fix issue with XAarray 0.16.2 by pinning to XAarray 0.16.1

.github/.codecov.yml, .github/workflows/test.yml, README.md
- add codecov
- setup codecov badge
=> add codecov

datacube_alchemist/worker.py
* Handle the case where you want to push scenes from a single product to a queue
=> Add handling of querying for a single product

datacube_alchemist/worker.py
It'd be nice to have a way to run tests against a database easier... and against AWS infra...
Anyhow, this should be good.
=> Fix issue search per product

examples/wofs_ls.alchemist.yaml, requirements.txt
* Increment wofs to include this: https://github.com/GeoscienceAustralia/wofs/releases/tag/1.6.4
* Set example flags
=> Update wofs to handle dsm nodata

Dockerfile, setup.cfg
* Make EO Datasets 0.22.0 a hard dependency in the setup.cfg
=> Make eod>=0.22.0 explicit

constraints.txt, datacube_alchemist/cli.py, datacube_alchemist/worker.py, requirements.txt
A bit of a brutal way to handle this, but should work. I'm not sure about the exceptions that might be raised.
=> Add exception handling to exit on AWS errors

datacube_alchemist/transforms.py
using the correct dataset (s2 nrt, not the s2 barest earth) to remove -999 and -/+infinite values
=> fixing filtering changes in alchemist transform

Dockerfile, constraints.txt, examples/fc_ls.alchemist.yaml, requirements.txt
* Update FC version to 1.3.6
* Update GDAL docker base to 3.3.3
* Local testing done, works fine
=> Update FC to 1.3.6 and update Docker base

datacube_alchemist/cli.py, datacube_alchemist/worker.py
This allows passing a small python expression to the command to filter
out any unwanted datasets before sending them to SQS.
Currently in DEA, our Water Observations datasets are only
created for scenes with a high geometric accuracy, BUT, this
filtering is implemented in an SQS Subscription and not in
Alchemist.
I'd like to move this filtering capability into
the Alchemist configuration file to ensure it is always used
for certain products, so this is a trial and first step.
=> Improve add-missing-to-queue with a dataset predicate filter

datacube_alchemist/_utils.py
Add version and path to sns attrs such that the indexing sqs can filter by them.
=> add version and path to sns attrs

.github/dependabot.yml, .pre-commit-config.yaml, Makefile, examples/archive/wofs_config_sentinel2b_alex.yaml, examples/wofs_ls.alchemist.yaml, requirements.txt, setup.cfg
=> fix(linting): Update pre-commit

.github/workflows/test-and-push.yml
Use the right file names for
requirements, and add setup.cfg
and pyproject.toml.
=> CI: fix file patterns
